# estimated states message



# Time of data acquisition

Header header



# Data

float32 est_mot_pos_left

float32 est_mot_pos_right

float32 est_mot_vel_left

float32 est_mot_vel_right

float32 est_hip_pos_left

float32 est_hip_pos_right

float32 est_hip_vel_left

float32 est_hip_vel_right

float32 est_hip_torque_left

float32 est_hip_torque_right

float32 est_imu_pos_roll

float32 est_imu_pos_pitch

float32 est_imu_pos_yaw

float32 est_imu_vel_roll

float32 est_imu_vel_pitch

float32 est_imu_vel_yaw

float32 est_imu_lin_acc_x

float32 est_imu_lin_acc_y

float32 est_imu_lin_acc_z

float32 est_wheel_pos_left

float32 est_wheel_pos_right

float32 est_wheel_vel_left

float32 est_wheel_vel_right

float32 est_wheel_pos_left_prev

float32 est_wheel_pos_right_prev

float32 est_theta_left

float32 est_theta_right

float32 est_theta_mean

float32 est_theta_dot_mean

float32 est_filt_theta_dot_mean

float32 est_lin_vel

float32 est_filt_lin_vel

float32 est_ang_vel

float32 est_filt_ang_vel

float32 est_robot_x_pos

float32 est_robot_y_pos

float32 est_robot_gamma_orient

float32 est_robot_x_pos_prev

float32 est_robot_y_pos_prev

float32 est_robot_gamma_orient_prev

float32 est_robot_rho

float32 est_robot_psi

float32 est_robot_beta

float32 est_robot_s_pos

float32 est_imu_drift_yaw

float32 est_imu_pitch_offset

float32 est_imu_pitch_offset_cad_error

float32 est_filt_mot_pos_left

float32 est_filt_mot_pos_right

float32 est_filt_mot_pos_left_prev

float32 est_filt_mot_pos_right_prev

float32 est_mot_pos_ave

float32 est_mot_vel_ave